version: '3.9'

services:
    db:
        image: mariadb:latest
        restart: on-failure
        environment:
            MARIADB_USER: root
            MARIADB_PASSWORD: rootsecret
            MARIADB_ROOT_PASSWORD: rootsecret
        ports:
            - 3306:3306
    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        ports:
            - 8080:80
        environment:
            PMA_PORT: 80
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 300M
